import { getPdfWorkerClient, recentsStore, type RecentFileEntry } from "@pdfloom/core";
import { Button, Card, IconButton, Mark, cn, toast } from "@pdfloom/ui";
import {
  BadgeDollarSign,
  BriefcaseBusiness,
  Cpu,
  FileCheck,
  FileLock2,
  FilePlus2,
  FileSignature,
  FileText,
  FolderOpen,
  Home,
  ImagePlus,
  Landmark,
  Receipt,
  ScrollText,
  ShieldBan,
  ShieldCheck,
  Trash2,
  UploadCloud,
  WifiOff,
  type LucideIcon,
} from "lucide-react";
import { useEffect, useState, type DragEvent } from "react";
import { Link } from "react-router-dom";
import { useLoomStore } from "../app/store";
import { CreateFromTextDialog } from "../features/convert/CreateFromTextDialog";
import { useImageFilePicker } from "../features/convert/useImageFilePicker";

const TRUST_BADGES = [
  { icon: ShieldCheck, label: "100% local & private" },
  { icon: Cpu, label: "Free AI, no account" },
  { icon: WifiOff, label: "Works offline" },
];

interface TemplateInfo {
  file: string;
  name: string;
  description: string;
  icon: LucideIcon;
  /** Surfaced in the larger "Recommended" tier above the full template grid. */
  featured?: boolean;
}

// Bundled, statically-hosted starter documents — generated by
// apps/web/scripts/generate-templates.mjs, shipped as real fillable PDFs in
// public/templates/ so browsing/using them needs no backend. None of these
// are official government forms; each carries its own in-document
// disclaimer (see the generator script for the exact wording).
const TEMPLATES: TemplateInfo[] = [
  { file: "residential-lease.pdf", name: "Residential Lease", description: "Landlord/tenant lease agreement", icon: Home, featured: true },
  { file: "mutual-nda.pdf", name: "Mutual NDA", description: "Non-disclosure agreement for two parties", icon: FileLock2, featured: true },
  { file: "simple-invoice.pdf", name: "Invoice", description: "Line-item invoice with totals", icon: Receipt, featured: true },
  { file: "employment-offer-letter.pdf", name: "Employment Offer Letter", description: "Offer terms for a new hire", icon: BriefcaseBusiness, featured: true },
  { file: "general-release.pdf", name: "General Release", description: "Release-of-claims agreement", icon: FileCheck },
  { file: "contractor-tax-info.pdf", name: "Contractor Tax Info", description: "Unofficial W-9-style info request", icon: Landmark },
  { file: "power-of-attorney.pdf", name: "Power of Attorney", description: "Appoint someone to act on your behalf", icon: FileSignature },
  { file: "last-will-testament.pdf", name: "Last Will & Testament", description: "Simple will template", icon: ScrollText },
  { file: "bill-of-sale.pdf", name: "Bill of Sale", description: "Document a sale of goods", icon: BadgeDollarSign },
  { file: "promissory-note.pdf", name: "Promissory Note", description: "Loan repayment agreement", icon: Receipt },
  { file: "non-compete-agreement.pdf", name: "Non-Compete Agreement", description: "Restrict competing activity", icon: ShieldBan },
];

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  const units = ["KB", "MB", "GB"];
  let value = bytes / 1024;
  let unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex++;
  }
  return `${value.toFixed(value >= 10 ? 0 : 1)} ${units[unitIndex]}`;
}

function formatRelativeTime(timestampMs: number): string {
  const diffSeconds = Math.round((timestampMs - Date.now()) / 1000);
  const formatter = new Intl.RelativeTimeFormat(undefined, { numeric: "auto" });
  const divisions: [number, Intl.RelativeTimeFormatUnit][] = [
    [60, "second"],
    [60, "minute"],
    [24, "hour"],
    [7, "day"],
    [4.34524, "week"],
    [12, "month"],
    [Number.POSITIVE_INFINITY, "year"],
  ];
  let duration = diffSeconds;
  for (const [amount, unit] of divisions) {
    if (Math.abs(duration) < amount) return formatter.format(Math.round(duration), unit);
    duration /= amount;
  }
  return formatter.format(Math.round(duration), "year");
}

export function WelcomeScreen() {
  const [isDraggingOver, setIsDraggingOver] = useState(false);
  const [recents, setRecents] = useState<RecentFileEntry[]>([]);
  const [loadingTemplate, setLoadingTemplate] = useState<string | null>(null);
  const [createFromTextOpen, setCreateFromTextOpen] = useState(false);
  const openViaPicker = useLoomStore((s) => s.openViaPicker);
  const openOpenedFile = useLoomStore((s) => s.openOpenedFile);
  const storage = useLoomStore((s) => s.storage);
  const loadError = useLoomStore((s) => s.loadError);
  const isLoading = useLoomStore((s) => s.isLoading);

  useEffect(() => {
    void recentsStore.list().then(setRecents);
  }, []);

  useEffect(() => {
    if (loadError) toast.error("Couldn't open this PDF", loadError);
  }, [loadError]);

  const handleDrop = async (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    setIsDraggingOver(false);
    const file = [...event.dataTransfer.files].find((f) => f.type === "application/pdf" || f.name.toLowerCase().endsWith(".pdf"));
    if (!file) {
      toast.warning("That's not a PDF", "Drop a .pdf file to open it.");
      return;
    }
    const opened = await storage.openFromFile(file);
    await openOpenedFile(opened);
  };

  const handleCreateFromImages = async (images: { bytes: Uint8Array; type: "png" | "jpg" }[]) => {
    try {
      const client = await getPdfWorkerClient();
      const bytes = await client.imagesToPdf(images, { mode: "auto" });
      const file = new File([bytes as BlobPart], "Untitled from images.pdf", { type: "application/pdf" });
      const opened = await storage.openFromFile(file);
      await openOpenedFile(opened);
    } catch (error) {
      toast.error("Couldn't create a PDF from those images", error instanceof Error ? error.message : undefined);
    }
  };
  const imagePicker = useImageFilePicker((images) => void handleCreateFromImages(images));

  const handleOpenTemplate = async (template: TemplateInfo) => {
    setLoadingTemplate(template.file);
    try {
      const response = await fetch(`/templates/${template.file}`);
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const blob = await response.blob();
      const file = new File([blob], template.file, { type: "application/pdf" });
      const opened = await storage.openFromFile(file);
      await openOpenedFile(opened);
    } catch {
      toast.error("Couldn't load this template", "Check your connection and try again.");
    } finally {
      setLoadingTemplate(null);
    }
  };

  const handleRemoveRecent = async (id: string) => {
    await recentsStore.remove(id);
    setRecents((prev) => prev.filter((r) => r.id !== id));
  };

  const handleClearRecents = async () => {
    await recentsStore.clear();
    setRecents([]);
  };

  const handleOpenRecent = async (entry: RecentFileEntry) => {
    const handle = await recentsStore.getHandle(entry.id);
    if (!handle) {
      toast.info("Locate the file again", "Your browser doesn't support reopening files without picking them.");
      await openViaPicker();
      return;
    }
    try {
      const permission = await handle.queryPermission({ mode: "read" });
      const granted = permission === "granted" || (await handle.requestPermission({ mode: "read" })) === "granted";
      if (!granted) {
        toast.warning("Permission needed", "PDFLoom needs permission to reopen this file.");
        return;
      }
      const file = await handle.getFile();
      const opened = await storage.openFromFile(file, handle);
      await openOpenedFile(opened);
    } catch {
      toast.error("Couldn't reopen this file", "It may have been moved, renamed, or deleted.");
      await recentsStore.remove(entry.id);
      setRecents((prev) => prev.filter((r) => r.id !== entry.id));
    }
  };

  const featuredTemplates = TEMPLATES.filter((t) => t.featured);
  const otherTemplates = TEMPLATES.filter((t) => !t.featured);

  return (
    <div className="relative flex h-full w-full overflow-y-auto bg-bg p-8">
      {/* Masks scrolled content behind the floating AccountButton cluster
          (fixed right-3 top-16, see AccountButton.tsx) instead of letting
          template cards visibly collide with it on mobile, where this is
          the one full-bleed scrollable page without its own sticky header
          to naturally reserve that band. Desktop's centered layout doesn't
          hit this — hidden there so it never adds an unnecessary seam. */}
      <div
        aria-hidden
        className="pointer-events-none fixed inset-x-0 top-0 z-[140] h-28 bg-gradient-to-b from-bg via-bg/90 to-transparent md:hidden"
      />
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 overflow-hidden"
        style={{
          background:
            "radial-gradient(60rem 34rem at 18% 8%, color-mix(in srgb, var(--loom-primary) 16%, transparent), transparent 60%), " +
            "radial-gradient(48rem 30rem at 88% 92%, color-mix(in srgb, var(--loom-ai) 12%, transparent), transparent 60%)",
        }}
      />

      <div className="relative m-auto grid w-full max-w-4xl gap-12 md:grid-cols-[1.2fr_1fr]">
        <div className="flex flex-col gap-6">
          <Link to="/" className="flex w-fit items-center gap-4" aria-label="PDFLoom home">
            <Mark size={48} className="rounded-(--radius-md) shadow-(--shadow-panel)" />
            <div>
              <div className="font-serif text-display font-semibold leading-none tracking-tight text-text">PDFLoom</div>
              <div className="mt-1.5 text-sm text-text-faint">Weave every page</div>
            </div>
          </Link>

          <div
            onDragOver={(e) => {
              e.preventDefault();
              setIsDraggingOver(true);
            }}
            onDragLeave={() => setIsDraggingOver(false)}
            onDrop={(e) => void handleDrop(e)}
            className={cn(
              "flex flex-col items-center justify-center gap-5 rounded-(--radius-xl) border-2 border-dashed p-12 text-center shadow-(--shadow-panel) transition-colors",
              isDraggingOver ? "border-primary bg-primary-muted" : "border-border bg-bg-elevated",
            )}
          >
            <UploadCloud className="h-9 w-9 text-text-faint" />
            <p className="max-w-sm text-sm text-text-muted">
              Drop a PDF here, or open one from your device. Everything runs locally in your browser — nothing is
              ever uploaded.
            </p>
            <div className="flex items-center gap-2">
              <Button variant="primary" size="lg" onClick={() => void openViaPicker()} disabled={isLoading}>
                <FolderOpen className="h-4 w-4" />
                {isLoading ? "Opening…" : "Open a PDF"}
              </Button>
              <Button variant="secondary" size="lg" onClick={() => imagePicker.open()} disabled={isLoading}>
                <ImagePlus className="h-4 w-4" />
                From images
              </Button>
              <Button variant="secondary" size="lg" onClick={() => setCreateFromTextOpen(true)} disabled={isLoading}>
                <FilePlus2 className="h-4 w-4" />
                From text
              </Button>
            </div>
            {imagePicker.input}
          </div>

          <div className="flex flex-wrap items-center gap-x-6 gap-y-2 px-1">
            {TRUST_BADGES.map(({ icon: Icon, label }) => (
              <div key={label} className="flex items-center gap-1.5 text-xs text-text-faint">
                <Icon className="h-3.5 w-3.5" />
                {label}
              </div>
            ))}
            <a href="/#desktop" className="text-xs text-text-faint underline decoration-dotted hover:text-text">
              Prefer a desktop app?
            </a>
          </div>

          <div className="flex flex-col gap-2">
            <h2 className="px-1 text-heading font-semibold text-text">Recommended templates</h2>
            <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
              {featuredTemplates.map((template) => (
                <Card
                  key={template.file}
                  icon={template.icon}
                  title={template.name}
                  description={loadingTemplate === template.file ? "Loading…" : template.description}
                  size="md"
                  onClick={() => void handleOpenTemplate(template)}
                  className={loadingTemplate !== null ? "pointer-events-none opacity-50" : undefined}
                />
              ))}
            </div>
          </div>

          <div className="flex flex-col gap-2">
            <h2 className="px-1 text-sm font-semibold uppercase tracking-wide text-text-faint">More templates</h2>
            <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">
              {otherTemplates.map((template) => (
                <Card
                  key={template.file}
                  icon={template.icon}
                  title={template.name}
                  description={loadingTemplate === template.file ? "Loading…" : template.description}
                  size="sm"
                  onClick={() => void handleOpenTemplate(template)}
                  className={loadingTemplate !== null ? "pointer-events-none opacity-50" : undefined}
                />
              ))}
            </div>
          </div>
        </div>

        <div className="flex min-w-0 flex-col gap-2 rounded-(--radius-xl) border border-border bg-bg-elevated/60 p-4">
          <div className="flex items-center justify-between px-1">
            <h2 className="text-heading font-semibold text-text">Recent</h2>
            {recents.length > 0 && (
              <button type="button" onClick={() => void handleClearRecents()} className="text-xs text-text-faint underline decoration-dotted hover:text-text">
                Clear all
              </button>
            )}
          </div>
          {recents.length === 0 ? (
            <p className="px-1 text-sm text-text-faint">Files you open will show up here.</p>
          ) : (
            <table className="w-full table-fixed text-left text-sm">
              <thead>
                <tr className="text-xs text-text-faint">
                  <th className="w-auto pb-2 pr-2 font-medium">Name</th>
                  <th className="w-20 pb-2 pr-2 text-right font-medium">Opened</th>
                  <th className="w-9 pb-2" />
                </tr>
              </thead>
              <tbody>
                {recents.map((entry) => (
                  <tr
                    key={entry.id}
                    onClick={() => void handleOpenRecent(entry)}
                    className="cursor-pointer border-t border-border hover:bg-surface-hover"
                  >
                    <td className="py-2 pr-2">
                      <span className="flex items-center gap-2">
                        <FileText className="h-4 w-4 shrink-0 text-text-faint" />
                        <span className="min-w-0 flex-1">
                          <span className="block truncate text-text">{entry.name}</span>
                          <span className="block text-xs text-text-faint">
                            {entry.pageCount} {entry.pageCount === 1 ? "page" : "pages"} · {formatBytes(entry.sizeBytes)}
                          </span>
                        </span>
                      </span>
                    </td>
                    <td className="py-2 pr-2 text-right align-top text-xs text-text-faint">{formatRelativeTime(entry.lastOpenedAt)}</td>
                    <td className="py-2 text-right align-top">
                      <IconButton
                        icon={<Trash2 />}
                        label="Remove from recents"
                        size="sm"
                        onClick={(e) => {
                          e.stopPropagation();
                          void handleRemoveRecent(entry.id);
                        }}
                      />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>
      <CreateFromTextDialog open={createFromTextOpen} onOpenChange={setCreateFromTextOpen} />
    </div>
  );
}
