import { getPdfWorkerClient, recentsStore, type RecentFileEntry } from "@pdfloom/core";
import { Button, Card, IconButton, Mark, cn, toast } from "@pdfloom/ui";
import {
  Ambulance,
  ArrowRightLeft,
  Award,
  BadgeDollarSign,
  Ban,
  Briefcase,
  BriefcaseBusiness,
  Boxes,
  Building,
  Building2,
  BookText,
  Calculator,
  CalendarCheck,
  CalendarClock,
  ChevronDown,
  CircleArrowUp,
  ClipboardCheck,
  ClipboardList,
  ClipboardPlus,
  ClipboardX,
  Clock3,
  Cpu,
  CreditCard,
  DoorOpen,
  FileCheck,
  FileClock,
  FileDiff,
  FileHeart,
  FileLock2,
  FilePlus,
  FilePlus2,
  FileBadge,
  FileSearch,
  FileSignature,
  FileText,
  FileUser,
  Flag,
  FolderOpen,
  Gavel,
  Gift,
  GraduationCap,
  Hammer,
  HandCoins,
  Handshake,
  HardHat,
  HeartHandshake,
  HeartPulse,
  Home,
  IdCard,
  ImagePlus,
  Landmark,
  Laptop,
  ListChecks,
  LogOut,
  Megaphone,
  MessageSquareWarning,
  MessagesSquare,
  Notebook,
  Package,
  PawPrint,
  PhoneCall,
  PiggyBank,
  Pill,
  PlaneTakeoff,
  Receipt,
  ReceiptText,
  RefreshCw,
  Scale,
  ScrollText,
  Search,
  SearchCheck,
  Send,
  ShieldAlert,
  ShieldBan,
  ShieldCheck,
  Siren,
  Stamp,
  Stethoscope,
  StickyNote,
  Store,
  Syringe,
  TestTube,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  Undo2,
  UserMinus,
  UserPlus,
  UserRoundCheck,
  Users,
  UsersRound,
  Video,
  Wallet,
  WifiOff,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import { useEffect, useState, type DragEvent } from "react";
import { Link } from "react-router-dom";
import { useLoomStore } from "../app/store";
import { CreateFromTextDialog } from "../features/convert/CreateFromTextDialog";
import { useImageFilePicker } from "../features/convert/useImageFilePicker";

const TRUST_BADGES = [
  { icon: ShieldCheck, label: "100% local & private" },
  { icon: Cpu, label: "Free AI, no account" },
  { icon: WifiOff, label: "Works offline" },
];

interface TemplateInfo {
  file: string;
  name: string;
  description: string;
  icon: LucideIcon;
  category: string;
  /** Surfaced in the larger "Recommended" tier above the full template grid. */
  featured?: boolean;
}

// Order here is also the display order of category sections below.
const TEMPLATE_CATEGORIES = [
  "Business & Administrative",
  "Legal & Contracts",
  "Financial & Billing",
  "Real Estate & Property",
  "Human Resources & Onboarding",
  "Healthcare & Medical",
  "Education & Training",
  "Logistics & Trade",
  "Operations & Field Services",
  "Corporate & Governance",
  "Insurance & Claims",
  "Procurement & Bidding",
  "Personal & Lifestyle",
] as const;

// One representative icon per category header — purely a wayfinding aid
// (the collapsed list is otherwise just text), not a new color system: every
// header icon stays in the same neutral tone regardless of category.
const CATEGORY_ICONS: Record<(typeof TEMPLATE_CATEGORIES)[number], LucideIcon> = {
  "Business & Administrative": Briefcase,
  "Legal & Contracts": Scale,
  "Financial & Billing": Wallet,
  "Real Estate & Property": Home,
  "Human Resources & Onboarding": UserPlus,
  "Healthcare & Medical": HeartPulse,
  "Education & Training": BookText,
  "Logistics & Trade": Truck,
  "Operations & Field Services": Wrench,
  "Corporate & Governance": Building2,
  "Insurance & Claims": ShieldAlert,
  "Procurement & Bidding": Store,
  "Personal & Lifestyle": Users,
};

// Bundled, statically-hosted starter documents — generated by
// apps/web/scripts/generate-templates.mjs, shipped as real fillable PDFs in
// public/templates/ so browsing/using them needs no backend. None of these
// are official government forms; each carries its own in-document
// disclaimer (see the generator script for the exact wording).
const TEMPLATES: TemplateInfo[] = [
  { file: "residential-lease.pdf", name: "Residential Lease", description: "Landlord/tenant lease agreement", icon: Home, category: "Real Estate & Property", featured: true },
  { file: "mutual-nda.pdf", name: "Mutual NDA", description: "Non-disclosure agreement for two parties", icon: FileLock2, category: "Legal & Contracts", featured: true },
  { file: "simple-invoice.pdf", name: "Invoice", description: "Line-item invoice with totals", icon: Receipt, category: "Financial & Billing", featured: true },
  { file: "employment-offer-letter.pdf", name: "Employment Offer Letter", description: "Offer terms for a new hire", icon: BriefcaseBusiness, category: "Human Resources & Onboarding", featured: true },
  { file: "general-release.pdf", name: "General Release", description: "Release-of-claims agreement", icon: FileCheck, category: "Legal & Contracts" },
  { file: "contractor-tax-info.pdf", name: "Contractor Tax Info", description: "Unofficial W-9-style info request", icon: Landmark, category: "Financial & Billing" },
  { file: "power-of-attorney.pdf", name: "Power of Attorney", description: "Appoint someone to act on your behalf", icon: FileSignature, category: "Legal & Contracts" },
  { file: "last-will-testament.pdf", name: "Last Will & Testament", description: "Simple will template", icon: ScrollText, category: "Legal & Contracts" },
  { file: "bill-of-sale.pdf", name: "Bill of Sale", description: "Document a sale of goods", icon: BadgeDollarSign, category: "Legal & Contracts" },
  { file: "promissory-note.pdf", name: "Promissory Note", description: "Loan repayment agreement", icon: Receipt, category: "Financial & Billing" },
  { file: "non-compete-agreement.pdf", name: "Non-Compete Agreement", description: "Restrict competing activity", icon: ShieldBan, category: "Legal & Contracts" },
  { file: "master-service-agreement.pdf", name: "Master Service Agreement", description: "Umbrella terms for ongoing work", icon: Scale, category: "Legal & Contracts" },
  { file: "liability-waiver.pdf", name: "Liability Waiver", description: "Release of claims for an activity", icon: ShieldAlert, category: "Legal & Contracts" },
  { file: "billing-statement.pdf", name: "Billing Statement", description: "Itemized charges for a billing period", icon: FileClock, category: "Financial & Billing" },
  { file: "purchase-order.pdf", name: "Purchase Order", description: "Formal order request to a vendor", icon: ClipboardList, category: "Financial & Billing" },
  { file: "commercial-lease.pdf", name: "Commercial Lease", description: "Lease agreement for business premises", icon: Building2, category: "Real Estate & Property" },
  { file: "property-disclosure.pdf", name: "Property Disclosure", description: "Seller's disclosure of property condition", icon: FileSearch, category: "Real Estate & Property" },
  { file: "rental-application.pdf", name: "Rental Application", description: "Screen a prospective tenant", icon: FileUser, category: "Real Estate & Property" },
  { file: "move-in-move-out-checklist.pdf", name: "Move-In/Move-Out Checklist", description: "Room-by-room condition record", icon: ListChecks, category: "Real Estate & Property" },
  { file: "tenant-ledger.pdf", name: "Tenant Ledger", description: "Rent payment history for a tenant", icon: Notebook, category: "Real Estate & Property" },
  { file: "maintenance-request.pdf", name: "Maintenance Request", description: "Tenant-submitted repair request", icon: Hammer, category: "Real Estate & Property" },
  { file: "pet-addendum.pdf", name: "Pet Addendum", description: "Add a pet to an existing lease", icon: PawPrint, category: "Real Estate & Property" },
  { file: "eviction-notice.pdf", name: "Eviction Notice", description: "Notice to pay rent or vacate", icon: DoorOpen, category: "Real Estate & Property" },
  { file: "rent-increase-notice.pdf", name: "Rent Increase Notice", description: "Notify a tenant of a new rent amount", icon: CircleArrowUp, category: "Real Estate & Property" },
  { file: "security-deposit-return.pdf", name: "Security Deposit Return", description: "Itemized deposit deductions", icon: Undo2, category: "Real Estate & Property" },
  { file: "lease-renewal.pdf", name: "Lease Renewal", description: "Extend an existing lease", icon: RefreshCw, category: "Real Estate & Property" },
  { file: "property-inspection-report.pdf", name: "Property Inspection Report", description: "Detailed condition inspection", icon: SearchCheck, category: "Real Estate & Property" },
  { file: "hoa-violation-notice.pdf", name: "HOA Violation Notice", description: "Notify an owner of a bylaw violation", icon: Megaphone, category: "Real Estate & Property" },
  { file: "roommate-agreement.pdf", name: "Roommate Agreement", description: "Split rent and house rules", icon: UsersRound, category: "Real Estate & Property" },
  { file: "short-term-rental-agreement.pdf", name: "Short-Term Rental Agreement", description: "Terms for a guest stay", icon: CalendarClock, category: "Real Estate & Property" },
  { file: "rent-receipt.pdf", name: "Rent Receipt", description: "Proof of a rent payment", icon: ReceiptText, category: "Real Estate & Property" },
  { file: "quote-estimate.pdf", name: "Quote / Estimate", description: "Priced scope before a job starts", icon: Calculator, category: "Business & Administrative" },
  { file: "receipt.pdf", name: "Receipt", description: "Proof of payment received", icon: ReceiptText, category: "Business & Administrative" },
  { file: "timesheet.pdf", name: "Timesheet", description: "Daily hours for a pay period", icon: Clock3, category: "Business & Administrative" },
  { file: "expense-report.pdf", name: "Expense Report", description: "Itemized reimbursable expenses", icon: Wallet, category: "Business & Administrative" },
  { file: "reference-letter.pdf", name: "Reference Letter", description: "Vouch for someone's character or skills", icon: Award, category: "Business & Administrative" },
  { file: "resignation-letter.pdf", name: "Resignation Letter", description: "Formally notify of your departure", icon: LogOut, category: "Business & Administrative" },
  { file: "meeting-agenda.pdf", name: "Meeting Agenda", description: "Structured plan for a meeting", icon: CalendarCheck, category: "Business & Administrative" },
  { file: "budget-request-form.pdf", name: "Budget Request Form", description: "Request funding for a purpose", icon: PiggyBank, category: "Business & Administrative" },
  { file: "internal-memo.pdf", name: "Internal Memo", description: "Short internal announcement", icon: StickyNote, category: "Business & Administrative" },
  { file: "change-order-form.pdf", name: "Change Order Form", description: "Document a change to a project's scope", icon: FileDiff, category: "Business & Administrative" },
  { file: "independent-contractor-agreement.pdf", name: "Independent Contractor Agreement", description: "Terms for a freelance engagement", icon: Briefcase, category: "Legal & Contracts" },
  { file: "purchase-agreement.pdf", name: "Purchase Agreement", description: "Sale of goods or business assets", icon: Handshake, category: "Legal & Contracts" },
  { file: "partnership-agreement.pdf", name: "Partnership Agreement", description: "Form a business partnership", icon: UserRoundCheck, category: "Legal & Contracts" },
  { file: "operating-agreement-llc.pdf", name: "LLC Operating Agreement", description: "Govern an LLC's internal operations", icon: Building, category: "Legal & Contracts" },
  { file: "employment-contract.pdf", name: "Employment Contract", description: "Full terms of employment", icon: BookText, category: "Legal & Contracts" },
  { file: "affidavit.pdf", name: "Affidavit", description: "Sworn written statement", icon: Stamp, category: "Legal & Contracts" },
  { file: "cease-and-desist-letter.pdf", name: "Cease and Desist Letter", description: "Formally demand conduct stop", icon: MessageSquareWarning, category: "Legal & Contracts" },
  { file: "demand-letter.pdf", name: "Demand Letter", description: "Formal demand before legal action", icon: Gavel, category: "Legal & Contracts" },
  { file: "settlement-agreement.pdf", name: "Settlement Agreement", description: "Resolve a dispute between two parties", icon: FileCheck, category: "Legal & Contracts" },
  { file: "notary-acknowledgment.pdf", name: "Notary Acknowledgment", description: "General-reference notarial certificate", icon: FileBadge, category: "Legal & Contracts" },
  { file: "contract-addendum.pdf", name: "Contract Addendum", description: "Amend an existing agreement", icon: FilePlus, category: "Legal & Contracts" },
  { file: "job-application-form.pdf", name: "Job Application", description: "Candidate application intake form", icon: UserPlus, category: "Human Resources & Onboarding" },
  { file: "performance-evaluation.pdf", name: "Performance Evaluation", description: "Employee review with ratings", icon: ClipboardCheck, category: "Human Resources & Onboarding" },
  { file: "patient-intake-form.pdf", name: "Patient Intake Form", description: "New patient history and contact info", icon: HeartPulse, category: "Healthcare & Medical" },
  { file: "hipaa-acknowledgment.pdf", name: "HIPAA Acknowledgment", description: "Notice of privacy practices receipt", icon: ShieldCheck, category: "Healthcare & Medical" },
  { file: "bill-of-lading.pdf", name: "Bill of Lading", description: "Shipment receipt and terms of carriage", icon: Truck, category: "Logistics & Trade" },
  { file: "packing-slip.pdf", name: "Packing Slip", description: "Itemized contents of a shipment", icon: Package, category: "Logistics & Trade" },
  { file: "work-order-signoff.pdf", name: "Work Order Sign-Off", description: "Confirm completed field work", icon: Wrench, category: "Operations & Field Services" },
  { file: "safety-incident-report.pdf", name: "Safety Incident Report", description: "Document a workplace incident", icon: TriangleAlert, category: "Operations & Field Services" },
  { file: "board-meeting-minutes.pdf", name: "Board Meeting Minutes", description: "Record of a board meeting", icon: Users, category: "Corporate & Governance" },
  { file: "stock-purchase-agreement.pdf", name: "Stock Purchase Agreement", description: "Purchase and sale of company shares", icon: TrendingUp, category: "Corporate & Governance" },
  { file: "insurance-claim-intake.pdf", name: "Insurance Claim Intake", description: "First report of a loss", icon: Siren, category: "Insurance & Claims" },
  { file: "proof-of-loss.pdf", name: "Proof of Loss", description: "Itemized statement of a claimed loss", icon: ClipboardX, category: "Insurance & Claims" },
  { file: "vendor-registration-form.pdf", name: "Vendor Registration", description: "Onboard a new supplier", icon: Store, category: "Procurement & Bidding" },
  { file: "subcontractor-agreement.pdf", name: "Subcontractor Agreement", description: "Terms for subcontracted project work", icon: HardHat, category: "Procurement & Bidding" },
  { file: "employee-tax-withholding.pdf", name: "Employee Tax Withholding Form", description: "Unofficial W-4-style withholding worksheet", icon: Landmark, category: "Human Resources & Onboarding" },
  { file: "employee-handbook-acknowledgment.pdf", name: "Employee Handbook Acknowledgment", description: "Confirm receipt of the handbook", icon: BookText, category: "Human Resources & Onboarding" },
  { file: "termination-notice.pdf", name: "Termination Notice", description: "Formally notify of employment termination", icon: UserMinus, category: "Human Resources & Onboarding" },
  { file: "background-check-authorization.pdf", name: "Background Check Authorization", description: "Consent to a pre-employment background check", icon: IdCard, category: "Human Resources & Onboarding" },
  { file: "training-attendance-sheet.pdf", name: "Training Attendance Sheet", description: "Sign-in sheet for a training session", icon: GraduationCap, category: "Human Resources & Onboarding" },
  { file: "disciplinary-action-form.pdf", name: "Disciplinary Action Form", description: "Document a workplace policy violation", icon: TriangleAlert, category: "Human Resources & Onboarding" },
  { file: "promotion-request-form.pdf", name: "Promotion Request Form", description: "Request and justify an employee promotion", icon: TrendingUp, category: "Human Resources & Onboarding" },
  { file: "exit-interview-form.pdf", name: "Exit Interview Form", description: "Structured feedback from a departing employee", icon: DoorOpen, category: "Human Resources & Onboarding" },
  { file: "remote-work-agreement.pdf", name: "Remote Work Agreement", description: "Terms for a remote or hybrid arrangement", icon: Laptop, category: "Human Resources & Onboarding" },
  { file: "medical-history-form.pdf", name: "Medical History Form", description: "Personal and family medical history intake", icon: FileHeart, category: "Healthcare & Medical" },
  { file: "insurance-information-form.pdf", name: "Insurance Information Form", description: "Collect primary and secondary insurance details", icon: ClipboardPlus, category: "Healthcare & Medical" },
  { file: "consent-for-treatment.pdf", name: "Consent for Treatment", description: "Patient consent to medical evaluation and care", icon: Stethoscope, category: "Healthcare & Medical" },
  { file: "prescription-request-form.pdf", name: "Prescription Refill Request", description: "Request a medication refill", icon: Pill, category: "Healthcare & Medical" },
  { file: "vaccination-record.pdf", name: "Vaccination Record", description: "Track vaccines administered over time", icon: Syringe, category: "Healthcare & Medical" },
  { file: "lab-requisition-form.pdf", name: "Lab Requisition Form", description: "Order lab tests for a patient", icon: TestTube, category: "Healthcare & Medical" },
  { file: "referral-form.pdf", name: "Referral Form", description: "Refer a patient to a specialist", icon: PhoneCall, category: "Healthcare & Medical" },
  { file: "discharge-summary.pdf", name: "Discharge Summary", description: "Summarize care and follow-up after discharge", icon: ClipboardCheck, category: "Healthcare & Medical" },
  { file: "medical-billing-form.pdf", name: "Medical Billing Form", description: "Itemized statement of medical charges", icon: ReceiptText, category: "Healthcare & Medical" },
  { file: "telehealth-consent.pdf", name: "Telehealth Consent", description: "Consent to receive care via telehealth", icon: Video, category: "Healthcare & Medical" },
  { file: "allergy-information-form.pdf", name: "Allergy Information Form", description: "Record known allergies and reactions", icon: Ban, category: "Healthcare & Medical" },
  { file: "emergency-contact-form.pdf", name: "Emergency Contact Form", description: "Emergency contacts for a patient's care", icon: Ambulance, category: "Healthcare & Medical" },
  { file: "loan-application.pdf", name: "Loan Application", description: "Apply for a personal, auto, or business loan", icon: Landmark, category: "Financial & Billing" },
  { file: "credit-authorization.pdf", name: "Credit Authorization Form", description: "Authorize a credit report check", icon: CreditCard, category: "Financial & Billing" },
  { file: "wire-transfer-form.pdf", name: "Wire Transfer Form", description: "Request an outgoing wire transfer", icon: ArrowRightLeft, category: "Financial & Billing" },
  { file: "budget-template.pdf", name: "Budget Template", description: "Track income and expenses for a period", icon: Wallet, category: "Financial & Billing" },
  { file: "audit-checklist.pdf", name: "Audit Checklist", description: "Internal audit review checklist", icon: ListChecks, category: "Financial & Billing" },
  { file: "invoice-financing-form.pdf", name: "Invoice Financing Form", description: "Request financing against an outstanding invoice", icon: HandCoins, category: "Financial & Billing" },
  { file: "compliance-certification.pdf", name: "Compliance Certification", description: "Certify compliance for a reporting period", icon: ShieldCheck, category: "Financial & Billing" },
  { file: "kyc-form.pdf", name: "KYC Form", description: "Know Your Customer identity verification", icon: IdCard, category: "Financial & Billing" },
  { file: "aml-questionnaire.pdf", name: "AML Questionnaire", description: "Anti-money-laundering risk questionnaire", icon: FileSearch, category: "Financial & Billing" },
  { file: "vendor-payment-request.pdf", name: "Vendor Payment Request", description: "Request payment approval for a vendor invoice", icon: Send, category: "Financial & Billing" },
  { file: "project-charter.pdf", name: "Project Charter", description: "Define a project's objective, scope, and milestones", icon: FileSignature, category: "Operations & Field Services" },
  { file: "action-item-log.pdf", name: "Action Item Log", description: "Track action items, owners, and due dates", icon: ListChecks, category: "Operations & Field Services" },
  { file: "risk-register.pdf", name: "Risk Register", description: "Log project risks, likelihood, and mitigation plans", icon: ShieldAlert, category: "Operations & Field Services" },
  { file: "project-change-request.pdf", name: "Project Change Request", description: "Request and approve a change to project scope", icon: FileDiff, category: "Operations & Field Services" },
  { file: "project-status-report.pdf", name: "Project Status Report", description: "Report progress, blockers, and next steps", icon: TrendingUp, category: "Operations & Field Services" },
  { file: "issue-log.pdf", name: "Issue Log", description: "Track open issues, owners, and priority", icon: MessageSquareWarning, category: "Operations & Field Services" },
  { file: "project-budget-tracker.pdf", name: "Project Budget Tracker", description: "Track budgeted vs. actual spend by category", icon: Calculator, category: "Operations & Field Services" },
  { file: "stakeholder-register.pdf", name: "Stakeholder Register", description: "Log stakeholders, roles, and influence", icon: UsersRound, category: "Operations & Field Services" },
  { file: "operational-checklist.pdf", name: "Operational Checklist", description: "General-purpose sign-off checklist", icon: ClipboardList, category: "Operations & Field Services" },
  { file: "sop-template.pdf", name: "SOP Template", description: "Document a standard operating procedure", icon: BookText, category: "Operations & Field Services" },
  { file: "root-cause-analysis.pdf", name: "Root Cause Analysis", description: "Investigate and document an incident's root cause", icon: SearchCheck, category: "Operations & Field Services" },
  { file: "meeting-minutes.pdf", name: "Meeting Minutes", description: "General-purpose meeting minutes and action items", icon: Notebook, category: "Business & Administrative" },
  { file: "general-consent-form.pdf", name: "General Consent Form", description: "Consent to participate in an activity or service", icon: FileCheck, category: "Personal & Lifestyle" },
  { file: "event-registration-form.pdf", name: "Event Registration Form", description: "Register an attendee for an event", icon: CalendarCheck, category: "Personal & Lifestyle" },
  { file: "complaint-form.pdf", name: "Complaint Form", description: "Submit a formal complaint", icon: Flag, category: "Personal & Lifestyle" },
  { file: "survey-form.pdf", name: "Survey Form", description: "Structured survey with rating-scale questions", icon: ClipboardList, category: "Personal & Lifestyle" },
  { file: "membership-application.pdf", name: "Membership Application", description: "Apply for membership in an organization", icon: UserPlus, category: "Personal & Lifestyle" },
  { file: "donation-form.pdf", name: "Donation Form", description: "Record a one-time or recurring donation", icon: HandCoins, category: "Personal & Lifestyle" },
  { file: "volunteer-application.pdf", name: "Volunteer Application", description: "Apply to volunteer with an organization", icon: HeartHandshake, category: "Personal & Lifestyle" },
  { file: "gift-certificate.pdf", name: "Gift Certificate", description: "Issue a gift certificate for goods or services", icon: Gift, category: "Personal & Lifestyle" },
  { file: "personal-budget.pdf", name: "Personal Budget", description: "Track personal monthly income and expenses", icon: PiggyBank, category: "Personal & Lifestyle" },
  { file: "household-inventory.pdf", name: "Household Inventory", description: "Record belongings and value for insurance or estate planning", icon: Boxes, category: "Personal & Lifestyle" },
  { file: "emergency-plan.pdf", name: "Household Emergency Plan", description: "Contacts, meeting points, and key info for emergencies", icon: Siren, category: "Personal & Lifestyle" },
  { file: "travel-consent-for-minors.pdf", name: "Minor Travel Consent Form", description: "Parental consent for a minor to travel", icon: PlaneTakeoff, category: "Personal & Lifestyle" },
];

// A small CSS-3D "stack of pages" in place of a static drop-zone icon — a
// literal nod to the "Weave every page" wordmark rather than decoration for
// its own sake. Idles with a slow float (loom-float, packages/ui
// tokens.css); dragging a file over the drop zone genuinely fans the pages
// out (`active`), so the one animated flourish on this screen is tied to
// real interaction state instead of running for its own sake. Pure
// CSS transforms — no canvas/WebGL, so no new rendering dependency or
// GPU-availability risk for what's otherwise a static landing screen.
function PageStack({ active }: { active: boolean }) {
  const pages = [
    { rotate: -10, x: -16, tint: "from-primary/35 to-primary/10" },
    { rotate: -3, x: -5, tint: "from-ai/30 to-ai/5" },
    { rotate: 4, x: 6, tint: "from-primary/40 to-primary/15" },
    { rotate: 11, x: 17, tint: "from-ai/35 to-ai/10" },
  ];
  return (
    <div className="loom-float relative h-16 w-32" style={{ perspective: "600px" }} aria-hidden>
      {pages.map((p, i) => (
        <div
          key={i}
          className={cn(
            "absolute left-1/2 top-1/2 h-14 w-11 rounded-(--radius-sm) border border-white/15 bg-gradient-to-br shadow-(--shadow-sm) transition-transform duration-500 ease-out",
            p.tint,
          )}
          style={{
            transform: `translate(-50%, -50%) translateX(${active ? p.x * 2 : p.x}px) rotate(${active ? p.rotate * 0.5 : p.rotate}deg) translateZ(${i * 6}px)`,
            zIndex: i,
          }}
        />
      ))}
    </div>
  );
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  const units = ["KB", "MB", "GB"];
  let value = bytes / 1024;
  let unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex++;
  }
  return `${value.toFixed(value >= 10 ? 0 : 1)} ${units[unitIndex]}`;
}

function formatRelativeTime(timestampMs: number): string {
  const diffSeconds = Math.round((timestampMs - Date.now()) / 1000);
  const formatter = new Intl.RelativeTimeFormat(undefined, { numeric: "auto" });
  const divisions: [number, Intl.RelativeTimeFormatUnit][] = [
    [60, "second"],
    [60, "minute"],
    [24, "hour"],
    [7, "day"],
    [4.34524, "week"],
    [12, "month"],
    [Number.POSITIVE_INFINITY, "year"],
  ];
  let duration = diffSeconds;
  for (const [amount, unit] of divisions) {
    if (Math.abs(duration) < amount) return formatter.format(Math.round(duration), unit);
    duration /= amount;
  }
  return formatter.format(Math.round(duration), "year");
}

export function WelcomeScreen({ onOpenMultiDocChat }: { onOpenMultiDocChat?: () => void } = {}) {
  const [isDraggingOver, setIsDraggingOver] = useState(false);
  const [recents, setRecents] = useState<RecentFileEntry[]>([]);
  const [loadingTemplate, setLoadingTemplate] = useState<string | null>(null);
  const [createFromTextOpen, setCreateFromTextOpen] = useState(false);
  const [templateSearch, setTemplateSearch] = useState("");
  // Categories start collapsed — with 60+ templates across a dozen
  // categories, an all-expanded grid was the "too long" the beautification
  // request called out. A search always shows its matches regardless of
  // this set (see `isExpanded` below), so searching never fights collapsing.
  const [expandedCategories, setExpandedCategories] = useState<Set<string>>(new Set());
  const openViaPicker = useLoomStore((s) => s.openViaPicker);
  const openOpenedFile = useLoomStore((s) => s.openOpenedFile);
  const storage = useLoomStore((s) => s.storage);
  const loadError = useLoomStore((s) => s.loadError);
  const isLoading = useLoomStore((s) => s.isLoading);

  useEffect(() => {
    void recentsStore.list().then(setRecents);
  }, []);

  useEffect(() => {
    if (loadError) toast.error("Couldn't open this PDF", loadError);
  }, [loadError]);

  const handleDrop = async (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    setIsDraggingOver(false);
    const file = [...event.dataTransfer.files].find((f) => f.type === "application/pdf" || f.name.toLowerCase().endsWith(".pdf"));
    if (!file) {
      toast.warning("That's not a PDF", "Drop a .pdf file to open it.");
      return;
    }
    const opened = await storage.openFromFile(file);
    await openOpenedFile(opened);
  };

  const handleCreateFromImages = async (images: { bytes: Uint8Array; type: "png" | "jpg" }[]) => {
    try {
      const client = await getPdfWorkerClient();
      const bytes = await client.imagesToPdf(images, { mode: "auto" });
      const file = new File([bytes as BlobPart], "Untitled from images.pdf", { type: "application/pdf" });
      const opened = await storage.openFromFile(file);
      await openOpenedFile(opened);
    } catch (error) {
      toast.error("Couldn't create a PDF from those images", error instanceof Error ? error.message : undefined);
    }
  };
  const imagePicker = useImageFilePicker((images) => void handleCreateFromImages(images));

  const handleOpenTemplate = async (template: TemplateInfo) => {
    setLoadingTemplate(template.file);
    try {
      const response = await fetch(`/templates/${template.file}`);
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const blob = await response.blob();
      const file = new File([blob], template.file, { type: "application/pdf" });
      const opened = await storage.openFromFile(file);
      await openOpenedFile(opened);
    } catch {
      toast.error("Couldn't load this template", "Check your connection and try again.");
    } finally {
      setLoadingTemplate(null);
    }
  };

  const handleRemoveRecent = async (id: string) => {
    await recentsStore.remove(id);
    setRecents((prev) => prev.filter((r) => r.id !== id));
  };

  const handleClearRecents = async () => {
    await recentsStore.clear();
    setRecents([]);
  };

  const handleOpenRecent = async (entry: RecentFileEntry) => {
    const handle = await recentsStore.getHandle(entry.id);
    if (!handle) {
      toast.info("Locate the file again", "Your browser doesn't support reopening files without picking them.");
      await openViaPicker();
      return;
    }
    try {
      const permission = await handle.queryPermission({ mode: "read" });
      const granted = permission === "granted" || (await handle.requestPermission({ mode: "read" })) === "granted";
      if (!granted) {
        toast.warning("Permission needed", "PDFLoom needs permission to reopen this file.");
        return;
      }
      const file = await handle.getFile();
      const opened = await storage.openFromFile(file, handle);
      await openOpenedFile(opened);
    } catch {
      toast.error("Couldn't reopen this file", "It may have been moved, renamed, or deleted.");
      await recentsStore.remove(entry.id);
      setRecents((prev) => prev.filter((r) => r.id !== entry.id));
    }
  };

  const featuredTemplates = TEMPLATES.filter((t) => t.featured);
  const otherTemplates = TEMPLATES.filter((t) => !t.featured);
  const query = templateSearch.trim().toLowerCase();
  const searchedTemplates = query
    ? otherTemplates.filter((t) => t.name.toLowerCase().includes(query) || t.description.toLowerCase().includes(query) || t.category.toLowerCase().includes(query))
    : otherTemplates;
  // Grouped by category (in TEMPLATE_CATEGORIES' own order) rather than one
  // flat grid — with 27 non-featured templates across 10 categories, a
  // single undifferentiated grid stopped being genuinely browsable once the
  // library grew past the original 7.
  const templatesByCategory = TEMPLATE_CATEGORIES.map((category) => ({
    category,
    templates: searchedTemplates.filter((t) => t.category === category),
  })).filter((group) => group.templates.length > 0);
  const allExpanded = templatesByCategory.length > 0 && templatesByCategory.every((g) => expandedCategories.has(g.category));

  const toggleCategory = (category: string) => {
    setExpandedCategories((prev) => {
      const next = new Set(prev);
      if (next.has(category)) next.delete(category);
      else next.add(category);
      return next;
    });
  };

  return (
    <div className="relative flex h-full w-full overflow-y-auto bg-bg p-8">
      {/* Masks scrolled content behind the floating AccountButton cluster
          (fixed right-3 top-16, see AccountButton.tsx) instead of letting
          template cards visibly collide with it on mobile, where this is
          the one full-bleed scrollable page without its own sticky header
          to naturally reserve that band. Desktop's centered layout doesn't
          hit this — hidden there so it never adds an unnecessary seam. */}
      <div
        aria-hidden
        className="pointer-events-none fixed inset-x-0 top-0 z-[140] h-28 bg-gradient-to-b from-bg via-bg/90 to-transparent md:hidden"
      />
      {/* Two independently-drifting gradient blobs (rather than one static
          combined background) — a slow, ambient "alive" quality behind the
          content that never demands attention or moves fast enough to
          distract from reading. loom-drift/-reverse (packages/ui tokens.css)
          both no-op under prefers-reduced-motion. */}
      <div
        aria-hidden
        className="loom-drift pointer-events-none absolute inset-0 overflow-hidden"
        style={{ background: "radial-gradient(60rem 34rem at 18% 8%, color-mix(in srgb, var(--loom-primary) 16%, transparent), transparent 60%)" }}
      />
      <div
        aria-hidden
        className="loom-drift-reverse pointer-events-none absolute inset-0 overflow-hidden"
        style={{ background: "radial-gradient(48rem 30rem at 88% 92%, color-mix(in srgb, var(--loom-ai) 12%, transparent), transparent 60%)" }}
      />

      <div className="relative m-auto grid w-full max-w-4xl gap-12 md:grid-cols-[1.2fr_1fr]">
        <div className="flex flex-col gap-6">
          <Link to="/" className="flex w-fit items-center gap-4" aria-label="PDFLoom home">
            <Mark size={48} className="rounded-(--radius-md) shadow-(--shadow-panel)" />
            <div>
              <div className="font-serif text-display font-semibold leading-none tracking-tight text-text">PDFLoom</div>
              <div className="mt-1.5 text-sm text-text-faint">Weave every page</div>
            </div>
          </Link>

          <div
            onDragOver={(e) => {
              e.preventDefault();
              setIsDraggingOver(true);
            }}
            onDragLeave={() => setIsDraggingOver(false)}
            onDrop={(e) => void handleDrop(e)}
            className={cn(
              "flex flex-col items-center justify-center gap-5 rounded-(--radius-xl) border-2 border-dashed p-6 text-center shadow-(--shadow-panel) transition-colors sm:p-12",
              isDraggingOver ? "border-primary bg-primary-muted" : "border-border bg-bg-elevated",
            )}
          >
            <PageStack active={isDraggingOver} />
            <p className="max-w-sm text-sm text-text-muted">
              Drop a PDF here, or open one from your device. Everything runs locally in your browser — nothing is
              ever uploaded.
            </p>
            <div className="flex flex-wrap items-center justify-center gap-2">
              <Button variant="primary" size="lg" onClick={() => void openViaPicker()} disabled={isLoading}>
                <FolderOpen className="h-4 w-4" />
                {isLoading ? "Opening…" : "Open a PDF"}
              </Button>
              <Button variant="secondary" size="lg" onClick={() => imagePicker.open()} disabled={isLoading}>
                <ImagePlus className="h-4 w-4" />
                From images
              </Button>
              <Button variant="secondary" size="lg" onClick={() => setCreateFromTextOpen(true)} disabled={isLoading}>
                <FilePlus2 className="h-4 w-4" />
                From text
              </Button>
            </div>
            {imagePicker.input}
          </div>

          <div className="flex flex-wrap items-center gap-x-6 gap-y-2 px-1">
            {TRUST_BADGES.map(({ icon: Icon, label }) => (
              <div key={label} className="flex items-center gap-1.5 text-xs text-text-faint">
                <Icon className="h-3.5 w-3.5" />
                {label}
              </div>
            ))}
            <a href="/#desktop" className="text-xs text-text-faint underline decoration-dotted hover:text-text">
              Prefer a desktop app?
            </a>
            {onOpenMultiDocChat && (
              <button
                type="button"
                onClick={onOpenMultiDocChat}
                className="flex items-center gap-1.5 rounded-full border border-ai/30 bg-ai-muted px-2.5 py-1 text-xs font-medium text-ai transition-colors hover:bg-ai/15"
              >
                <MessagesSquare className="h-3.5 w-3.5" />
                Chat across documents
              </button>
            )}
          </div>

          <div className="flex flex-col gap-2">
            <h2 className="px-1 text-heading font-semibold text-text">Recommended templates</h2>
            <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
              {featuredTemplates.map((template) => (
                <Card
                  key={template.file}
                  icon={template.icon}
                  title={template.name}
                  description={loadingTemplate === template.file ? "Loading…" : template.description}
                  size="md"
                  onClick={() => void handleOpenTemplate(template)}
                  className={loadingTemplate !== null ? "pointer-events-none opacity-50" : undefined}
                />
              ))}
            </div>
          </div>

          <div className="flex flex-col gap-3">
            <div className="flex flex-col gap-2 px-1 sm:flex-row sm:items-center sm:justify-between">
              <div className="flex items-center gap-2">
                <h2 className="text-sm font-semibold uppercase tracking-wide text-text-faint">More templates</h2>
                <span className="text-xs text-text-faint">({otherTemplates.length})</span>
              </div>
              <div className="flex min-w-0 items-center gap-3">
                {templatesByCategory.length > 1 && !query && (
                  <button
                    type="button"
                    onClick={() =>
                      setExpandedCategories(allExpanded ? new Set() : new Set(templatesByCategory.map((g) => g.category)))
                    }
                    className="shrink-0 text-xs text-text-faint underline decoration-dotted hover:text-text"
                  >
                    {allExpanded ? "Collapse all" : "Expand all"}
                  </button>
                )}
                <div className="relative min-w-0 flex-1 sm:max-w-[220px]">
                  <Search className="pointer-events-none absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-text-faint" />
                  <input
                    type="text"
                    value={templateSearch}
                    onChange={(e) => setTemplateSearch(e.target.value)}
                    placeholder="Search templates…"
                    aria-label="Search templates"
                    className="h-8 w-full rounded-(--radius-sm) border border-border bg-bg-elevated py-1 pl-8 pr-2.5 text-xs text-text outline-none focus-visible:ring-2 focus-visible:ring-(--color-focus-ring)"
                  />
                </div>
              </div>
            </div>
            {templatesByCategory.length === 0 && (
              <p className="px-1 text-sm text-text-faint">No templates match "{templateSearch}".</p>
            )}
            <div className="flex flex-col gap-1 rounded-(--radius-lg) border border-border bg-bg-elevated/60">
              {templatesByCategory.map(({ category, templates }, index) => {
                const isExpanded = query.length > 0 || expandedCategories.has(category);
                const CategoryIcon = CATEGORY_ICONS[category as (typeof TEMPLATE_CATEGORIES)[number]] ?? Search;
                return (
                  <div key={category} className={cn("flex flex-col", index > 0 && "border-t border-border")}>
                    <button
                      type="button"
                      onClick={() => toggleCategory(category)}
                      aria-expanded={isExpanded}
                      className="flex items-center gap-2.5 px-3 py-2.5 text-left hover:bg-surface-hover"
                    >
                      <div className="relative flex h-6 w-6 shrink-0 items-center justify-center overflow-hidden rounded-(--radius-sm) bg-gradient-to-br from-primary/30 via-primary/10 to-transparent text-primary shadow-[inset_0_1px_0_0_rgba(255,255,255,0.18),inset_0_-6px_10px_-6px_rgba(0,0,0,0.15)]">
                        <CategoryIcon className="h-3.5 w-3.5" />
                      </div>
                      <span className="flex-1 text-sm font-medium text-text">{category}</span>
                      <span className="text-xs text-text-faint">{templates.length}</span>
                      <ChevronDown className={cn("h-3.5 w-3.5 shrink-0 text-text-faint transition-transform duration-100", isExpanded && "rotate-180")} />
                    </button>
                    {isExpanded && (
                      <div className="grid grid-cols-3 gap-1.5 px-3 pb-3 sm:grid-cols-4">
                        {templates.map((template) => (
                          <Card
                            key={template.file}
                            icon={template.icon}
                            title={template.name}
                            description={loadingTemplate === template.file ? "Loading…" : template.description}
                            size="xs"
                            onClick={() => void handleOpenTemplate(template)}
                            className={loadingTemplate !== null ? "pointer-events-none opacity-50" : undefined}
                          />
                        ))}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        <div className="flex min-w-0 flex-col gap-2 rounded-(--radius-xl) border border-border bg-bg-elevated/60 p-4">
          <div className="flex items-center justify-between px-1">
            <h2 className="text-heading font-semibold text-text">Recent</h2>
            {recents.length > 0 && (
              <button type="button" onClick={() => void handleClearRecents()} className="text-xs text-text-faint underline decoration-dotted hover:text-text">
                Clear all
              </button>
            )}
          </div>
          {recents.length === 0 ? (
            <p className="px-1 text-sm text-text-faint">Files you open will show up here.</p>
          ) : (
            <table className="w-full table-fixed text-left text-sm">
              <thead>
                <tr className="text-xs text-text-faint">
                  <th className="w-auto pb-2 pr-2 font-medium">Name</th>
                  <th className="w-20 pb-2 pr-2 text-right font-medium">Opened</th>
                  <th className="w-9 pb-2" />
                </tr>
              </thead>
              <tbody>
                {recents.map((entry) => (
                  <tr
                    key={entry.id}
                    onClick={() => void handleOpenRecent(entry)}
                    className="cursor-pointer border-t border-border hover:bg-surface-hover"
                  >
                    <td className="py-2 pr-2">
                      <span className="flex items-center gap-2">
                        <FileText className="h-4 w-4 shrink-0 text-text-faint" />
                        <span className="min-w-0 flex-1">
                          <span className="block truncate text-text">{entry.name}</span>
                          <span className="block text-xs text-text-faint">
                            {entry.pageCount} {entry.pageCount === 1 ? "page" : "pages"} · {formatBytes(entry.sizeBytes)}
                          </span>
                        </span>
                      </span>
                    </td>
                    <td className="py-2 pr-2 text-right align-top text-xs text-text-faint">{formatRelativeTime(entry.lastOpenedAt)}</td>
                    <td className="py-2 text-right align-top">
                      <IconButton
                        icon={<Trash2 />}
                        label="Remove from recents"
                        size="sm"
                        onClick={(e) => {
                          e.stopPropagation();
                          void handleRemoveRecent(entry.id);
                        }}
                      />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>
      <CreateFromTextDialog open={createFromTextOpen} onOpenChange={setCreateFromTextOpen} />
    </div>
  );
}
